version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-west-2:730335574269:task-definition/ecs-demo-1-EcsTaskDefinition-N9KjHvXa2A5s:2"
        LoadBalancerInfo:
          ContainerName: "codedeploy-ecs-demo-container"
          ContainerPort: 8080
