version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - 
  build:
    commands:
      - mvn package

artifacts:
  files:
    - target/codedeployecsdemo*